#!/bin/bash

echo -n "
choose option
    m) merge pdf files
    e) extract pages from pdf
    i) pdf to image
    x) exit
#?  "
read ops

case $ops in
    m)  echo "which files to merge?"
	read -a IN
	echo -n "provide name for output file:"
	read OUT
	pdfunite "${IN[@]}" $OUT.pdf
	;;
    e)  echo -n "name the pdf file to extract images from:"
	read IN
	echo -n "first page to extract:"
	read FIRST
	echo -n "last page to extract:"
	read LAST
	echo -n "provide name for output file:"
	read OUT
	pdfseparate -f $FIRST -l $LAST $IN $OUT%d.pdf
	;;
    i)	echo "coming soon"
	;;
    x)	exit
	;;
esac

