#!/bin/bash
tput clear
echo
echo "IMPORTANT: cd to the directory to be scanned before starting scan"

echo -n	"
	Choose option,	    
	    s) scan
	    u) update database
	    x) EXIT
#? "

read ops

case $ops in
    s) 
    echo -n "What to scan? :"
    read path
    clamscan --verbose --infected --phishing-sigs=yes --move=~/.viruses -r $path ;;
    u) sudo freshclam ;;
    x) exit ;;
esac
#--remove=yes
#--detect-pua=yes 
