#!/bin/sh

if [ "$1" = "-h" ]; then
	cat <<EOF>&2
Usage: ${0##*/} [OPTIONS]

Display weather forecast.

Use '${0##*/} :help' to list all options.

EOF
	exit
fi
if [[ ! $1 ]]; then
w3m wttr.in/Valsad | less
else
w3m wttr.in/"$1" | less
fi
