#!/bin/bash

w3m http://wttr.in/valsad | head -7 | tail -5 | awk '{ gsub("↑",""); gsub("↗",""); { gsub("→" ,""); gsub("↓ " ,""); gsub("↙ " ,""); gsub("↘ " ,""); gsub("← " ,""); gsub("↖" ,""); print $0}'}
